name: Deploy Next.js site to Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'
          cache-dependency-path: 'my-app/package-lock.json'
          
      - name: Install dependencies
        run: npm ci
        working-directory: my-app
        
      - name: Build the Next.js application
        run: npm run build
        working-directory: my-app
        
      - name: Upload the Next.js build output as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: github-pages
          path: my-app/out/
          
  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download the Next.js build output artifact
        uses: actions/download-artifact@v3
        with:
          name: github-pages
          path: out
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifact_name: github-pages
          preview: false
